# Generated by Django 3.2.20 on 2023-08-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=10)),
                ('tgt', models.CharField(max_length=10)),
                ('srcText', models.CharField(max_length=500)),
                ('tgtText', models.CharField(max_length=500)),
            ],
        ),
    ]
